services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./backend
    container_name: server_container
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    environment:
      MONGODB_URI: mongodb+srv://hiran86:WWE95nxt@cluster0.67pxs.mongodb.net/TravelPlanner?retryWrites=true&w=majority&appName=Cluster0

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - server
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules

volumes:
  mongo_data:
